[package]
name = "jdx-clt"
version = "0.4.0-alpha"
edition = "2021"

[[bin]]
name = "jdx"
path = "src/main.rs"

[dependencies]
jdx-rust = { git = "https://github.com/jeffreycshelton/jdx-rust", tag = "v0.3.0-alpha" }
image = "^0.23.14"
