[package]
name = "jdx-clt"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jdx-rust = { git = "https://github.com/jeffreycshelton/jdx-rust" }
