[package]
name = "jdx-clt"
version = "0.2.0"
edition = "2018"

[[bin]]
name = "jdx"
path = "src/main.rs"

[dependencies]
jdx-rust = { git = "https://github.com/jeffreycshelton/jdx-rust" }
image = "^0.23.14"
