[package]
name = "jdx-clt"
version = "0.4.0"
edition = "2021"

[[bin]]
name = "jdx"
path = "src/main.rs"

[dependencies]
jdx = { git = "https://github.com/jeffreycshelton/jdx-rust", tag = "v0.4.0" }
image = "^0.23.14"
